import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Deepak Negi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TDG9BNPP"
height="0" width="0" className='hidden'></iframe></noscript>
        {children}
      </body>
    </html>
  )
}
